---
server:
  port: 8112
  servlet:
    context-path: /api/catalogo
  forward-headers-strategy: framework
application:
  title: catalogo
  version: 1.0.0-SNAPSHOT
spring:
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 24h
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    lazy-initialization: true
  output:
    ansi:
      enabled: always
  datasource:
    url: ${CATALOGO_POSTGRES_URL}
    username: ${CATALOGO_POSTGRES_USER}
    password: ${CATALOGO_POSTGRES_PASSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        default_schema: dbo
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      org:
        hibernate:
          envers:
            store_data_at_delete: true
            default_schema: AUD
            audit_table_suffix: _AUD
    defer-datasource-initialization: false
  sql:
    init:
      platform: PostgreSQL
      mode: always
  hikari:
    minimumIdle: 1
    maximumPoolSize: 1
    idleTimeout: 30000
    maxLifetime: 1800000
    connectionTimeout: 80000
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    config:
      enabled: false
  feign:
    client:
      config:
        default:
          enabled: true
logging:
  level:
    root: INFO
    com.kalebsa: INFO
    org.springframework: INFO
    net.ttddyy.dsproxy.listener: debug
    org.springframework.context.i18n: DEBUG
eureka:
  client:
    enabled: false
management:
  tracing:
    sampling:
      probability: 1